services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: notes_db
      POSTGRES_USER: notes_user
      POSTGRES_PASSWORD: notes_pass
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 3s
      timeout: 3s
      retries: 10

  api:
    build: .
    env_file: .env
    environment:
      # <<< главное переопределение для контейнера >>>
      DATABASE_URL: postgresql+asyncpg://notes_user:notes_pass@db:5432/notes_db
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

volumes:
  pgdata:
